### ISSUE TITLE
Use the full height to draw sparklines

### ISSUE THREAD

**Issue by mklein994** [aftertheflood/sparks#19]
I know very little about typography, so bear with me. I'm looking to use this font instead of the Unicode block characters (`▁▂▃▄▅▆▇█`), and in comparing them, I'm finding that they don't line up. Here's an example of what I'm talking about: https://codepen.io/anon/pen/QaxXGj?editors=1100 (spark bar medium font on the left, Unicode blocks on the right)

![spark font height](https://user-images.githubusercontent.com/3069239/34912067-47340934-f89c-11e7-87f5-bd285f8eb286.png)

I realize that this is more of an artistic decision, given that these are supposed to be used inline with other text, but perhaps there can be an alternative version that uses the full height?

**Comment by michaelgallagher** [comment]
Hi @mklein994 – I'm not completely opposed to the idea of an alternate height set in principle, but practically speaking it would be a fair amount of work for a relatively small benefit. Also, with the current settings, all of the variations (bar, dot, dot-line) all have (very nearly) the same vertical size/scale, making it easier to use them together. Double also, as you mentioned, the intention for Spark is to use it in the context of text so having the bottom of the scale line up with the baseline and the top of the scale line up with the cap-height seems like the most useful way to size things (rather than fully utilising the entire em square height)
