### ISSUE TITLE
Dot-line medium broken in Apple Pages

### ISSUE THREAD

**Issue by benjaminkitt** [aftertheflood/sparks#4]
All styles seem to work well in Apple Pages except Dot-line medium. This may be an Apple problem, but thought I'd report it in case there's anything that can be done.

![image](https://user-images.githubusercontent.com/1332211/30331174-abf6acf2-979c-11e7-913c-fa0fbbb58762.png)

**Comment by Crydust** [comment]
My testing showed spark-dotline-medium only works for integers from 0 till 9 inclusive.
This works:
`Testing some spark lines 123{1,2,3,5}456`
This doesn't:
`Testing some spark lines 123{10,20,30,50}456`

**Comment by benjaminkitt** [comment]
Interesting, thanks!

**Comment by michaelgallagher** [comment]
That's right! So far the dot-line version only goes to 9. Making it go from 0–100 is next on my list of things to tackle.

**Comment by dutchbeachbum** [comment]
Hello, I am not very tech savvy but I really like the idea of these fonts. I installed them on my Windows 10 system, but the fonts don't seem to work WORD. Also how do I install the font using Dreamweaver? Not sure which file to download on to the server so that I can link the page to the font and CSS. Also the .class script I see is that to go on the webpage between the <head> section so that the browser knows what to do? Could someone please point me in the right direction?

**Comment by ghost** [comment]
Hi,

Have you looked at our readme to get it working in Word? We have also had a guide written by the community that you may find useful:

https://onlinejournalismblog.com/2017/09/21/how-to-use-the-atf-spark-font-for-creating-charts-with-only-text/#more-25179

Another example:
https://bl.ocks.org/maartenzam/ec47f50a9f16747a4ea77d565d38d613

Hope this helps.
