### ISSUE TITLE
Does not work in Adobe Illustrator

### ISSUE THREAD

**Issue by chrisalcantara** [aftertheflood/sparks#6]
Thank you for this great tool. The README said these fonts will work with Illustrator. However, when I installed and tried Spark in my AI file, nothing happens. 

Am I doing something wrong?

**Comment by michaelgallagher** [comment]
Hi @chrisalcantara – in Illustrator you may need to turn on contextual alternates. You can do that from the OpenType panel menu (Window > Type > OpenType). On my machine it is turned on by default, but I'm not sure if that is because I've used it before and it just stayed on. I'll add notes about this to readme, hopefully soon.

<img width="247" alt="illustrator-opentype-menu" src="https://user-images.githubusercontent.com/771600/30393566-7ebc3a96-98b8-11e7-9b18-34cf6b1550c4.png">
