### ISSUE TITLE
Regular text corrupted in Word 2016

### ISSUE THREAD

**Issue by brianwdavis** [aftertheflood/sparks#9]
The contextual alternatives are working, but the regular text is not. Any ideas?

![image](https://user-images.githubusercontent.com/13338560/30568721-cb6fc5f2-9ca4-11e7-86fc-301a26c6522e.png)

Microsoft Office 365 ProPlus
Version 1609
Word 2016 MSO (16.0.7329.1054) 32-bit

**Comment by michaelgallagher** [comment]
Ah, yes, so the text isn't corrupted, it just doesn't exist yet. I made a few letters so I could write things like 1st, 2nd, 3rd but that was as far as we got. Adding a full alphabet is something I plan on, but: 

1. it may only be uppercase since this was never intended to be a "normal" typeface – the numerals and few letters that are currently in there are more like small-caps in size – the letters etc. are probably best used as just the labels for the sparklines
2. I personally won't have time to work on the rest of the alphabet for a few weeks

I'll try to add a roadmap to the readme.

**Comment by brianwdavis** [comment]
Thanks for the reply. The fact that only the numerals and special glyphs were included wasn't clear in the demo page or the GitHub readme, so I assumed I just had a corrupted file. I think just a quick note to clarify is really all that's needed!
